##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/cloudify-cosmo/cloudify-fabric-plugin/archive/1.4.2.zip
        package_name: cloudify-fabric-plugin
        package_version: '1.4.2'
