##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/mabuaisha/cloudify-fabric-plugin/archive/debug-fabric-proxy-server.zip
        package_name: cloudify-fabric-plugin
        package_version: '1.5.1.dev0'
