##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/cloudify-cosmo/cloudify-fabric-plugin/archive/2.0.14.zip
        package_name: cloudify-fabric-plugin
        package_version: '2.0.14'
